{% set name = "tabulous" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tabulous-{{ version }}.tar.gz
  sha256: 4e915b3bbca487dc2e8934ec645d3b8a7a45c4a436fa9835aff1be88d540be77

build:
  entry_points:
    - tabulous=tabulous.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - appdirs >=1.4.4
    - collections-undo >=0.0.7
    - magicgui >=0.5.1
    - matplotlib-base >=3.1
    - numpy                       # Imported but not listed as requirement
    - pandas >=1.5.2
    - psygnal >=0.9.0
    - python >={{ python_min }}
    - qt-command-palette >=0.0.6
    - qtconsole
    - qtpy >=1.10.0
    - requests
    - superqt                     # Imported but not listed as requirement
    - tabulate
    - toml
    - typing-extensions           # Imported but not listed as requirement
    # Extras
    - scikit-learn >=1.1
    - scipy >=1.7
    - seaborn >=0.11

test:
  imports:
    - tabulous
  commands:
    - pip list
    - pip check
    - tabulous --help
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/tabulous
  summary: A table data viewer for Python
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hanjinliu/tabulous

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
